version: '2'

services:
  downstream:
    platform: linux/amd64
    image: nginx:alpine
    ports:
      - 8282:80
    network_mode: bridge

  proxy:
    platform: linux/amd64
    build: .
    ports:
      - 80:80
    environment:
      - OID_SESSION_SECRET=623q4hR325t36VsCD3g567922IC0073T
      - OID_SESSION_CHECK_SSI=off
      - OID_SESSION_NAME=oidc_auth

      - OID_REDIRECT_URI=http://${HOST_IP}/redirect
      - OID_DISCOVERY=http://${HOST_IP}:8080/realms/master/.well-known/openid-configuration
      - OID_CLIENT_ID=proxy
      - OID_CLIENT_SECRET=dz2p5AJ48Vw5FY7oGYMcbWaWLbcKAX29
      - OID_USE_PKCE=true

      - PROXY_HOST=${HOST_IP}
      - PROXY_PORT=8282
      - PROXY_PROTOCOL=http
    network_mode: bridge

  keycloak:
    platform: linux/amd64
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - 8080:8080
    environment:
    - KEYCLOAK_ADMIN=root
    - KEYCLOAK_ADMIN_PASSWORD=root
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    network_mode: bridge
